// dc_fifo.v

// Generated using ACDS version 22.1 915

`timescale 1 ps / 1 ps
module dc_fifo (
		input  wire [7:0] dc_fifo_0_in_data,               //            dc_fifo_0_in.data
		input  wire       dc_fifo_0_in_valid,              //                        .valid
		output wire       dc_fifo_0_in_ready,              //                        .ready
		input  wire       dc_fifo_0_in_startofpacket,      //                        .startofpacket
		input  wire       dc_fifo_0_in_endofpacket,        //                        .endofpacket
		input  wire [0:0] dc_fifo_0_in_error,              //                        .error
		input  wire       dc_fifo_0_in_clk_clk,            //        dc_fifo_0_in_clk.clk
		input  wire       dc_fifo_0_in_clk_reset_reset_n,  //  dc_fifo_0_in_clk_reset.reset_n
		output wire [7:0] dc_fifo_0_out_data,              //           dc_fifo_0_out.data
		output wire       dc_fifo_0_out_valid,             //                        .valid
		input  wire       dc_fifo_0_out_ready,             //                        .ready
		output wire       dc_fifo_0_out_startofpacket,     //                        .startofpacket
		output wire       dc_fifo_0_out_endofpacket,       //                        .endofpacket
		output wire [0:0] dc_fifo_0_out_error,             //                        .error
		input  wire       dc_fifo_0_out_clk_clk,           //       dc_fifo_0_out_clk.clk
		input  wire       dc_fifo_0_out_clk_reset_reset_n  // dc_fifo_0_out_clk_reset.reset_n
	);

	altera_avalon_dc_fifo #(
		.SYMBOLS_PER_BEAT   (1),
		.BITS_PER_SYMBOL    (8),
		.FIFO_DEPTH         (128),
		.CHANNEL_WIDTH      (0),
		.ERROR_WIDTH        (1),
		.USE_PACKETS        (1),
		.USE_IN_FILL_LEVEL  (0),
		.USE_OUT_FILL_LEVEL (0),
		.WR_SYNC_DEPTH      (3),
		.RD_SYNC_DEPTH      (3)
	) dc_fifo_0 (
		.in_clk            (dc_fifo_0_in_clk_clk),                 //        in_clk.clk
		.in_reset_n        (dc_fifo_0_in_clk_reset_reset_n),       //  in_clk_reset.reset_n
		.out_clk           (dc_fifo_0_out_clk_clk),                //       out_clk.clk
		.out_reset_n       (dc_fifo_0_out_clk_reset_reset_n),      // out_clk_reset.reset_n
		.in_data           (dc_fifo_0_in_data),                    //            in.data
		.in_valid          (dc_fifo_0_in_valid),                   //              .valid
		.in_ready          (dc_fifo_0_in_ready),                   //              .ready
		.in_startofpacket  (dc_fifo_0_in_startofpacket),           //              .startofpacket
		.in_endofpacket    (dc_fifo_0_in_endofpacket),             //              .endofpacket
		.in_error          (dc_fifo_0_in_error),                   //              .error
		.out_data          (dc_fifo_0_out_data),                   //           out.data
		.out_valid         (dc_fifo_0_out_valid),                  //              .valid
		.out_ready         (dc_fifo_0_out_ready),                  //              .ready
		.out_startofpacket (dc_fifo_0_out_startofpacket),          //              .startofpacket
		.out_endofpacket   (dc_fifo_0_out_endofpacket),            //              .endofpacket
		.out_error         (dc_fifo_0_out_error),                  //              .error
		.in_csr_address    (1'b0),                                 //   (terminated)
		.in_csr_read       (1'b0),                                 //   (terminated)
		.in_csr_write      (1'b0),                                 //   (terminated)
		.in_csr_readdata   (),                                     //   (terminated)
		.in_csr_writedata  (32'b00000000000000000000000000000000), //   (terminated)
		.out_csr_address   (1'b0),                                 //   (terminated)
		.out_csr_read      (1'b0),                                 //   (terminated)
		.out_csr_write     (1'b0),                                 //   (terminated)
		.out_csr_readdata  (),                                     //   (terminated)
		.out_csr_writedata (32'b00000000000000000000000000000000), //   (terminated)
		.in_empty          (1'b0),                                 //   (terminated)
		.out_empty         (),                                     //   (terminated)
		.in_channel        (1'b0),                                 //   (terminated)
		.out_channel       (),                                     //   (terminated)
		.space_avail_data  ()                                      //   (terminated)
	);

endmodule
