// sc_fifo.v

// Generated using ACDS version 23.1 991

`timescale 1 ps / 1 ps
module sc_fifo (
		input  wire        sc_fifo_0_clk_clk,           //       sc_fifo_0_clk.clk
		input  wire        sc_fifo_0_clk_reset_reset,   // sc_fifo_0_clk_reset.reset
		input  wire [2:0]  sc_fifo_0_csr_address,       //       sc_fifo_0_csr.address
		input  wire        sc_fifo_0_csr_read,          //                    .read
		input  wire        sc_fifo_0_csr_write,         //                    .write
		output wire [31:0] sc_fifo_0_csr_readdata,      //                    .readdata
		input  wire [31:0] sc_fifo_0_csr_writedata,     //                    .writedata
		input  wire [7:0]  sc_fifo_0_in_data,           //        sc_fifo_0_in.data
		input  wire        sc_fifo_0_in_valid,          //                    .valid
		output wire        sc_fifo_0_in_ready,          //                    .ready
		input  wire        sc_fifo_0_in_startofpacket,  //                    .startofpacket
		input  wire        sc_fifo_0_in_endofpacket,    //                    .endofpacket
		input  wire [0:0]  sc_fifo_0_in_error,          //                    .error
		output wire [7:0]  sc_fifo_0_out_data,          //       sc_fifo_0_out.data
		output wire        sc_fifo_0_out_valid,         //                    .valid
		input  wire        sc_fifo_0_out_ready,         //                    .ready
		output wire        sc_fifo_0_out_startofpacket, //                    .startofpacket
		output wire        sc_fifo_0_out_endofpacket,   //                    .endofpacket
		output wire [0:0]  sc_fifo_0_out_error          //                    .error
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (8),
		.FIFO_DEPTH          (2048),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (1),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (1),
		.EMPTY_LATENCY       (3),
		.USE_MEMORY_BLOCKS   (1),
		.USE_STORE_FORWARD   (1),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) sc_fifo_0 (
		.clk               (sc_fifo_0_clk_clk),           //       clk.clk
		.reset             (sc_fifo_0_clk_reset_reset),   // clk_reset.reset
		.csr_address       (sc_fifo_0_csr_address),       //       csr.address
		.csr_read          (sc_fifo_0_csr_read),          //          .read
		.csr_write         (sc_fifo_0_csr_write),         //          .write
		.csr_readdata      (sc_fifo_0_csr_readdata),      //          .readdata
		.csr_writedata     (sc_fifo_0_csr_writedata),     //          .writedata
		.in_data           (sc_fifo_0_in_data),           //        in.data
		.in_valid          (sc_fifo_0_in_valid),          //          .valid
		.in_ready          (sc_fifo_0_in_ready),          //          .ready
		.in_startofpacket  (sc_fifo_0_in_startofpacket),  //          .startofpacket
		.in_endofpacket    (sc_fifo_0_in_endofpacket),    //          .endofpacket
		.in_error          (sc_fifo_0_in_error),          //          .error
		.out_data          (sc_fifo_0_out_data),          //       out.data
		.out_valid         (sc_fifo_0_out_valid),         //          .valid
		.out_ready         (sc_fifo_0_out_ready),         //          .ready
		.out_startofpacket (sc_fifo_0_out_startofpacket), //          .startofpacket
		.out_endofpacket   (sc_fifo_0_out_endofpacket),   //          .endofpacket
		.out_error         (sc_fifo_0_out_error),         //          .error
		.almost_full_data  (),                            // (terminated)
		.almost_empty_data (),                            // (terminated)
		.in_empty          (1'b0),                        // (terminated)
		.out_empty         (),                            // (terminated)
		.in_channel        (1'b0),                        // (terminated)
		.out_channel       ()                             // (terminated)
	);

endmodule
